[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/ttyUSB1
upload_protocol = arduino
lib_deps =
    https://github.com/coryjfowler/MCP_CAN_lib.git
